### ISSUE TITLE
第一次运行正常，但是关掉SSH再打开运行脚本时出现以下情况

### ISSUE THREAD

**Issue by MakotoKo** [RikkaApps/FCM-for-Mojo#76]
module.js:471
    throw err;
    ^

Error: Cannot find module '../client.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new FFMConfig (/root/ffm/node/ffm-config.js:8:21)
    at Object.<anonymous> (/root/ffm/node/index.js:12:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by MakotoKo** [comment]
用winscp 删掉了/root/client.json后恢复正常，但再次运行时依旧出现上述问题

**Comment by kzw200015** [comment]
我也是，不过我重装后解决

**Comment by WordlessEcho** [comment]
请问你可以把 client.json 贴上来吗？（请记得对文件做一定的处理）
